import './globals.css'
import classnames from 'classnames'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={classnames(inter.className, 'w-full flex flex-col items-center px-5 md:px-0')}>{children}</body>
    </html>
  )
}
